// Auto-generated venue list
export const IPL_VENUES: string[] = [
  "Wankhede Stadium, Mumbai",
  "MA Chidambaram Stadium, Chepauk, Chennai",
  "Narendra Modi Stadium, Ahmedabad",
  "Eden Gardens, Kolkata",
  "Arun Jaitley Stadium, Delhi",
  "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow",
  "M Chinnaswamy Stadium, Bengaluru",
  "Rajiv Gandhi International Stadium, Uppal, Hyderabad",
  "Dr DY Patil Sports Academy, Mumbai",
  "Sawai Mansingh Stadium, Jaipur",
  "Brabourne Stadium, Mumbai",
  "Maharashtra Cricket Association Stadium, Pune",
  "Dubai International Cricket Stadium",
  "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
  "Sharjah Cricket Stadium",
  "Barsapara Cricket Stadium, Guwahati",
  "Zayed Cricket Stadium, Abu Dhabi",
  "Himachal Pradesh Cricket Association Stadium, Dharamsala",
  "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh",
  "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",
  "Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh",
];
